array_layout = "Block"
closure_block_indent_threshold = 1
fn_args_layout = "Block"
fn_args_paren_newline = false
fn_call_style = "Block"
generics_indent = "Block"
match_block_trailing_comma = true
reorder_imported_names = true
reorder_import = true
reorder_imports_in_group = true
struct_lit_style = "Block"
where_style = "Rfc"
wrap_comments = true
